apiVersion: v1
kind: Secret
metadata:
  name: agribora-prod-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: agribora-prod
  server: https://DOKS_ENDPOINT_HERE
  config: |
    {
      "bearerToken": "DOKS_SERVICE_ACCOUNT_TOKEN",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "DOKS_CA_DATA_BASE64"
      }
    }
